baseURL = "http://aliciahickey.com/"
languageCode = "en-us"
title = "Alicia Hickey's website"
theme = "aerial"

[params]
  name = "Alicia Hickey"
  about = "Data Scientist &nbsp;&bull;&nbsp; Agile Methodologies &nbsp;&bull;&nbsp; Berlin, Germany"
  copyright = "2019 Alicia Hickey"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "wewe"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/lonelypeanut"

[[params.social]]
  medium = "Medium"
  icon = "medium"
  link = "https://medium.com/@lonelypeanut"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/alicia-hickey/"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:hello@aliciahickey.com"

 